### ISSUE TITLE
Fail to create a database for PostgreSQL server

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#2180]
**OS:** Win10
**Build Version:** 20230919.6

**Repro Steps:**
1. Create one PostgreSQL server in VS Code.
2. Expand the above single server -> Expand "postgre" database -> Connect to this server.
3. Right click the PostgreSQL server -> Select "Create Database..." -> Enter a database name to create.
4. Check whether succeeds to create a database or not.

**Expect:**
Succeed to create a database for PostgreSQL server without any error.

**Actual:**
Fail to create a database for PostgreSQL server with an error.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/3953c8ae-e79a-4870-bff2-48acbb247558)

**More Info:**
This issue reproduces for both single and flexible PostgreSQL server.

**Comment by v-ruizh** [comment]
Verified this bug on a newer build 20230927.1, the error message changes. You can get the details from below.
The below error shows when creating a new database for Single PostgreSQL server.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/15aaf944-a73e-4009-b709-fda15eff4c27)
The below error shows when creating a new database for Flexible PostgreSQL server.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/4a831648-a28c-47e0-920a-b8a2d3a9d914)

**Comment by JasonYeMSFT** [comment]
I believe this has been fixed.

**Comment by v-ruizh** [comment]
Verified this bug on the latest build 20231017.2, this issue also reproduces. You can get the details from below.
The below error shows when creating a new database for Single PostgreSQL server.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/1f404f34-a3e3-4dc3-a100-92de8d9f27c3)
The below error shows when creating a new database for Flexible PostgreSQL server.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/d1728c0c-bdc6-42f9-a657-a2f30953d43f)

**Comment by HaydenBussard** [comment]
> I believe this has been fixed.

I am still getting this. My copy of MS Code is up to date. Azure extension installed a day or two ago.

**Comment by JasonYeMSFT** [comment]
I am still not able to reproduce this problem. The "ECONNRESET" error hints that it might have something to do with a transient network issue. If you can ever reproduce this issue, could you go to the Output panel in VSCode and get the output from the extension like my screenshot shows? It would help further investigate the issue if I can know which stage failed.

<img width="868" alt="image" src="https://github.com/microsoft/vscode-cosmosdb/assets/39359541/d134a6b8-4d5f-4519-82e1-143a2aba71de">

**Comment by v-ruizh** [comment]
@JasonYeMSFT Verified this issue on the current released Azure Databases extension **v0.20.0**, this issue also reproduces.
The repro steps and output show as below.
1. Create a PostgreSQL server.
2. Add the firewall rule to connect to the "postgre" database.
3. Create a new database for this PostgreSQL server.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/738aab0c-4b26-44ba-a29e-4d3f094e41da)

Can't verify this issue on the latest main branch build 20240109.2 due to the known bug https://github.com/microsoft/vscode-cosmosdb/issues/2209.

**Comment by JasonYeMSFT** [comment]
OK. It seems like the datebase creation was successful but the follow up access didn't work. Could you go to Azure Portal, navigate to the postgres database resource > Networking blade and see if the current IP detected by Azure Portal matches the IP address printed in the output? The IP detection logic we use may not guarantee that the IP address we add to the firewall rule is the actual IP address used to connect to the database.
 
<img width="299" alt="Screenshot 2024-01-11 at 11 53 59 AM" src="https://github.com/microsoft/vscode-cosmosdb/assets/39359541/a570795a-f043-477a-a9c0-4225b6e72c5c">

**Comment by v-ruizh** [comment]
Checked the current IP in Azure Portal, the current IP detected by Azure Portal matches the IP address printed in the output.

**Comment by JasonYeMSFT** [comment]
OK, however, unfortunately there is no way for us nor Portal to guarantee the IP address we detect will be used to connect. For everyone who encounters the ECONNRESET error, please consult your local network admin to see if they can help you figure out at which stage does the network reset happens.

**Comment by JasonYeMSFT** [comment]
I found a bug while looking into #2224. I am going to close this issue since it is more related to the firewall setting.
