### ISSUE TITLE
Mongo commands fail if there is more than one argument

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#383]
There's one open issue about projections being ignored for "find" commands here: https://github.com/Microsoft/vscode-cosmosdb/issues/214

However, its a somewhat larger issue because any "unrecognized" commands that use the mongo shell (instead of the rest api like "find") fail with an error like this:

![screen shot 2018-03-05 at 9 13 21 am](https://user-images.githubusercontent.com/11282622/36989521-ca7ffd84-2056-11e8-8caa-605dcbdf424b.png)

For example, run the example command from [here](https://docs.mongodb.com/manual/reference/method/db.collection.findOneAndUpdate/)
```
db.scores.findOneAndUpdate({ "name" : "A. MacDyver" }, { "$inc" : { "points" : 5 } }, { "sort" : { "points" : 1 } })
```

**Comment by PrashanthCorp** [comment]
Marking as closed, 
fixed by #460

**Comment by StephenWeatherford** [comment]
Note: This doesn't fix all commands yet, but does allow them as a general issue. If someone has a command that doesn't work with multiple arguments that you need to use, please file an issue.
