### ISSUE TITLE
Incomplete command breaks all other commands

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#611]
The changelog says: "Errors in one command in the scrapbook no longer stop functionality for other commands"

Perhaps I just found an edge case?
![screen shot 2018-05-04 at 2 34 06 pm](https://user-images.githubusercontent.com/11282622/39654064-4967e870-4fa8-11e8-946e-89c7485a3211.png)

The codelens is gone and I get this message when I try to run one of the complete commands
![screen shot 2018-05-04 at 2 34 54 pm](https://user-images.githubusercontent.com/11282622/39654087-62e94dca-4fa8-11e8-9d85-bbb51bb16149.png)

**Comment by StephenWeatherford** [comment]
#609.  I agree this hasn't been fixed for all cases.  I'll modify the changelog.

**Comment by StephenWeatherford** [comment]
The cannot read error should have been fixed (#591). Are you using the most recent version?  I get this:

Error near line 3, column 4, text 'test'. Please check syntax.

**Comment by EricJizbaMSFT** [comment]
Yeah - just updated to latest (aka 0.7.0 as shown in my screenshot) and still getting that error:
![screen shot 2018-05-04 at 3 49 20 pm](https://user-images.githubusercontent.com/11282622/39656154-c268c6f4-4fb2-11e8-9061-41c4f2fda81a.png)
